export const BeachPlaceholderData = [
  {
    beachAdvisory: null,
    beachId: 1,
    beachState: null,
    eColiCount: null,
    map: '43.585563,-79.540732',
    name: 'Marie Curtis Park East Beach',
    blueFlag: false,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 2,
    beachState: null,
    eColiCount: null,
    map: '43.637432,-79.455954',
    name: 'Sunnyside Beach',
    blueFlag: false,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 3,
    beachState: null,
    eColiCount: null,
    map: '43.619325,-79.393254',
    name: "Hanlan's Point Beach",
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 4,
    beachState: null,
    eColiCount: null,
    map: '43.612487,-79.382173',
    name: 'Gibraltar Point Beach',
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 5,
    beachState: null,
    eColiCount: null,
    map: '43.616072,-79.373826',
    name: 'Centre Island Beach',
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 6,
    beachState: null,
    eColiCount: null,
    map: '43.630088,-79.352318',
    name: "Ward's Island Beach",
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 7,
    beachState: null,
    eColiCount: null,
    map: '43.636742,-79.344117',
    name: 'Cherry Beach',
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 8,
    beachState: null,
    eColiCount: null,
    map: '43.66381,-79.305057',
    name: 'Woodbine Beaches',
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 9,
    beachState: null,
    eColiCount: null,
    map: '43.668559,-79.290057',
    name: 'Kew Balmy Beach',
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 10,
    beachState: null,
    eColiCount: null,
    map: '43.71363,-79.225948',
    name: "Bluffer's Beach Park",
    blueFlag: true,
    publishDate: null,
    sampleDate: null,
  },
  {
    beachAdvisory: null,
    beachId: 11,
    beachState: null,
    eColiCount: null,
    map: '43.793217,-79.118217',
    name: 'Rouge Beach',
    blueFlag: false,
    publishDate: null,
    sampleDate: null,
  },
];
